"""initial migration

Revision ID: 58737cd296ba
Revises: 
Create Date: 2024-06-12 22:53:09.318532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58737cd296ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('phone_Number', sa.String(length=50), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admins',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'IN_PROGRESS', 'COMPLETED', 'DELIVERED', name='orderstatus'), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_details', sa.String(length=100), nullable=False),
    sa.Column('order_address', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('admins')
    op.drop_table('users')
    # ### end Alembic commands ###
