name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r backend/requirements.txt

    - name: Generate .env file
      run: |
        echo "SECRET_KEY=$(openssl rand -base64 32)" > backend/API/.env
        echo "JWT_SECRET_KEY=$(openssl rand -base64 32)" >> backend/API/.env

    - name: Verify dependencies
      run: |
        source venv/bin/activate
        pip list

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s backend/API/test -p "*.py"
